version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=web_imdb
      - POSTGRES_USER=web_imdb
      - POSTGRES_PASSWORD=web_imdb
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=web_imdb
      - POSTGRES_USER=web_imdb
      - POSTGRES_PASSWORD=web_imdb
    depends_on:
      - db